# Generated by Django 3.2.16 on 2023-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images'),
        ),
    ]
