# Generated by Django 3.2.16 on 2023-02-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images'),
        ),
    ]
