# Generated by Django 3.2.16 on 2023-01-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230124_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
