# Generated by Django 3.2.16 on 2023-02-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Неправильно', max_length=255, unique=True, verbose_name='username'),
        ),
    ]
