# Generated by Django 3.2.16 on 2023-01-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
