# Generated by Django 3.2.16 on 2023-01-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staf',
            field=models.BooleanField(default=False, verbose_name='staf'),
        ),
    ]
