# Generated by Django 3.2.16 on 2023-01-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20230127_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', help_text='Ваша почта', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
