# Generated by Django 3.2.16 on 2023-01-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_user_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
