# Generated by Django 3.2.16 on 2023-01-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
